# Generated by Django 4.2.7 on 2026-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('event_name', models.CharField(max_length=500)),
                ('event_type', models.CharField(blank=True, default='Conference', max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=500)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('event_website', models.URLField(blank=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('traveler_name', models.CharField(default='Dr. Hisham Al Jadhey', max_length=300)),
                ('traveler_title', models.CharField(default='الرئيس التنفيذي للهيئة العامة للغذاء والدواء', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('report_subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('visit_objectives', models.JSONField(default=list)),
                ('country_info', models.JSONField(default=dict)),
                ('delegation', models.JSONField(default=list)),
                ('agenda', models.JSONField(default=list)),
                ('conference_data', models.JSONField(default=dict)),
                ('conference_tracks', models.JSONField(default=list)),
                ('sessions', models.JSONField(default=dict)),
                ('speakers', models.JSONField(default=list)),
                ('bilateral_meetings', models.JSONField(default=list)),
                ('consulate', models.JSONField(default=dict)),
                ('weather', models.JSONField(default=list)),
                ('prayer_times', models.JSONField(default=list)),
                ('previous_outcomes', models.JSONField(default=list)),
                ('attachments', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
