# Generated by Django 4.2.7 on 2026-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0005_rich_intelligence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bilateral_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='intel_global_significance',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='intel_long_term_value',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='intel_regulatory_impact',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='ns_institutional_positioning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='ns_investment_implications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='ns_regulatory_relevance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='ns_vision_alignment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='political_economic_orientation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='political_strategic_priorities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
